name: filemanager
description: Simple file manager application made with flutter.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.8+9

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  open_file: ^3.5.10
  google_fonts: ^6.1.0
  permission_handler: ^12.0.0+1
  device_info_plus: ^12.1.0
  shared_preferences: ^2.5.2
  flutter_speed_dial: ^7.0.0
  path_provider: ^2.1.5
  image: ^4.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_icons:
  android: true
  image_path: "assets/folder.png"
  adaptive_icon_background: "#ffffff"
